### ISSUE TITLE
Sync Integration

### ISSUE THREAD

**Issue by TimOliver** [realm/RealmTasks#1]
The use case scenario for Sync we're envisioning for this app is the same one as the official Clear app: 

> A user has downloaded the app onto their multiple iOS devices, and would like to ensure that any changes they perform on any device will be instantly updated to every other device.

The latest release of Realm Swift with Sync available from [Realm's private CocoaPods repo](https://github.com/realm/cocoapods-specs-private) will be the one used for this project.

Integrating Sync itself for this project should be relatively trivial. The app itself is simply a `UITableView` interface, so as long as Sync changes are exposed via the fine-grained notifications API, it should be a matter of simply joining the two inside the notification block.

For authentication, at the very beginning (and for testing purposes), one shared Sync session should be suitable. Down the line, we can start looking at ways to invisibly identity discrete users, using methods such as[ the user's iCloud ID token](https://github.com/realm/RealmClear/issues/10).

Change events would be responsible for:
- [x]  A new task is created and inserted from scratch (#11) 
- [x] An existing task's text is edited. (#12)
- [x] The sort order of the tasks is changed.  (#13)
- [x] A task is deleted. (#14)
